### ISSUE TITLE
Heroku - Push rejected, failed to compile Plone app

### ISSUE THREAD

**Issue by jamrockmedz** [plock/plock#23]
While:
  Installing.
  Getting section plone.
  Initializing section plone.
  Loading zc.buildout recipe entry plone.recipe.zope2instance:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 510, in install
    [self[part]['recipe'] for part in install_parts]
  File "/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1098, in __getitem__
    options._initialize()
  File "/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1202, in _initialize
    self.initialize()
  File "/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1208, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/zc.buildout-2.3.1-py2.7.egg/zc/buildout/buildout.py", line 1167, in _install_and_load
    req.project_name, group, entry)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2309, in load
    self.require(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2326, in require
    items = working_set.resolve(reqs, env, installer)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (setuptools 5.0.1 (/tmp/build_03f737e8b49527132d25fb4447dcc46f/eggs/setuptools-5.0.1-py2.7.egg), Requirement.parse('setuptools>=8.0'), set(['zc.buildout']))

 !     Push rejected, failed to compile Plone app

**Comment by aclark4life** [comment]
Working on this

**Comment by jamrockmedz** [comment]
Tried to resolve issue, resorted to starting a new project

**Comment by aclark4life** [comment]
Did that work for you?

**Comment by jamrockmedz** [comment]
Yes, the new project is working

On Tue, Jan 27, 2015 at 7:02 PM, Alex Clark <notifications@github.com>
wrote:

> Did that work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plock/plock/issues/23#issuecomment-71755580>.
>



-- 

Regards,
Percival Reid

**Comment by aclark4life** [comment]
Great
